[package]
name = "conn"
version = "0.0.0"
authors = ["Dung Ph <dungph@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
async-lock = "1.1.2"
async-std = "1.6.2"
async-mutex = "1.1.3"
